import { writeFileSync } from "node:fs";
import {
  DISTRIBUTIONS,
  empiricalQuantiles,
  PROBABILITIES,
  SAMPLE_COUNT,
  sampleDistributions,
} from "./quantile-sampling.js";

const samples = sampleDistributions(SAMPLE_COUNT);
const rows = DISTRIBUTIONS.map(
  (name) =>
    `  ${name}: Object.freeze(${JSON.stringify(empiricalQuantiles(samples[name]))}),`,
);
const code = `// Generated by npm run noise:calibrate. Never hand-tune distribution thresholds.
// 1,000,000 samples per profile; exact sampler and provenance in test/quantile-sampling.ts.
export const QUANTILE_PROVENANCE = Object.freeze({ samples: 1000000, sequenceSeed: 0x243f6a88, seedMin: 1, seedMax: 3, domainMin: -4096, domainMax: 4096, fractalOctaves: 5, warpOctaves: 2, lacunarity: 2, gain: 0.5, erosionStrength: 1 });
export const QUANTILE_PROBABILITIES: readonly number[] = Object.freeze(${JSON.stringify(PROBABILITIES)});
export const NOISE_QUANTILES = Object.freeze({
${rows.join("\n")}
});
export type NoiseDistribution = keyof typeof NOISE_QUANTILES;
`;
writeFileSync(
  new URL("../src/noise/quantiles.generated.ts", import.meta.url),
  code,
);
console.log(
  `Calibrated ${SAMPLE_COUNT.toLocaleString("en")} points for each of ${DISTRIBUTIONS.length} distributions.`,
);
for (const name of DISTRIBUTIONS) {
  const v = samples[name];
  console.log(
    `${name}: min=${v[0]}, median=${v[SAMPLE_COUNT / 2]}, max=${v[SAMPLE_COUNT - 1]}`,
  );
}
