import { mkdir, writeFile } from "node:fs/promises";
import { PSRD2_PROFILE } from "../src/noise/psrd2.js";
import {
  PSRD2_HELD_OUT_SEQUENCE_SEED,
  PSRD2_PROBABILITIES,
  PSRD2_SAMPLE_COUNT,
  PSRD2_SEQUENCE_SEED,
  psrd2Coverage,
  psrd2EmpiricalQuantiles,
  samplePsrd2,
} from "./psrd2-sampling.js";

const measured = psrd2EmpiricalQuantiles(samplePsrd2());
const provenance = {
  profile: PSRD2_PROFILE.id,
  sourceRevision: PSRD2_PROFILE.sourceRevision,
  sourceSha256: PSRD2_PROFILE.sourceSha256,
  samples: PSRD2_SAMPLE_COUNT,
  sequenceSeed: PSRD2_SEQUENCE_SEED,
  seedMin: 1,
  seedMax: 3,
  domainMin: -4096,
  domainMax: 4096,
  dimensions: 2,
  frequency: 1,
  gradientCount: PSRD2_PROFILE.gradientCount,
  quantileRank: "p*(samples-1), linear interpolation, numeric ascending sort",
  runtime: process.version,
};
const generated = [
  "// Generated by node --import tsx packages/shared/test/psrd2-calibrate.ts.",
  "// Separate, measured 1M-point PSRD2_PROFILE; do not reuse for other kernels or fractals.",
  `export const PSRD2_QUANTILE_PROVENANCE = Object.freeze(${JSON.stringify(provenance, null, 2)});`,
  `export const PSRD2_QUANTILE_PROBABILITIES: readonly number[] = Object.freeze(${JSON.stringify(PSRD2_PROBABILITIES)});`,
  `export const PSRD2_QUANTILES: readonly number[] = Object.freeze(${JSON.stringify(measured)});`,
  "",
].join("\n");
await writeFile(
  new URL("../src/noise/psrd2-quantiles.generated.ts", import.meta.url),
  generated,
);
const heldOut = samplePsrd2(100_000, PSRD2_HELD_OUT_SEQUENCE_SEED, 16);
const coverage = ([0.55, 0.8] as const).map((p) => {
  const index = PSRD2_PROBABILITIES.indexOf(p);
  const threshold = measured[index] as number;
  return {
    probability: p,
    threshold,
    achieved: psrd2Coverage(heldOut, threshold),
  };
});
const receipt = {
  provenance,
  probabilities: PSRD2_PROBABILITIES,
  quantiles: measured,
  heldOut: {
    sequenceSeed: PSRD2_HELD_OUT_SEQUENCE_SEED,
    seedMin: 17,
    seedMax: 19,
    samples: heldOut.length,
    coverage,
  },
};
const directory = new URL("../../../out/phase1-2-noise/", import.meta.url);
await mkdir(directory, { recursive: true });
await writeFile(
  new URL("calibration.json", directory),
  `${JSON.stringify(receipt, null, 2)}\n`,
);
console.info(receipt);
