// Generated by node --import tsx packages/shared/test/psrd2-calibrate.ts.
// Separate, measured 1M-point PSRD2_PROFILE; do not reuse for other kernels or fractals.
export const PSRD2_QUANTILE_PROVENANCE = Object.freeze({
  profile: "psrd2-nonperiodic-hash3-unit256-v1",
  sourceRevision: "419175a270862ce7ae692038fafafb42ec0427e9",
  sourceSha256:
    "3abb8a203480c79363677995f38c8ffeb1fd9d1eb941473a6f3c4a07532458a6",
  samples: 1000000,
  sequenceSeed: 3084996962,
  seedMin: 1,
  seedMax: 3,
  domainMin: -4096,
  domainMax: 4096,
  dimensions: 2,
  frequency: 1,
  gradientCount: 256,
  quantileRank: "p*(samples-1), linear interpolation, numeric ascending sort",
  runtime: "v24.18.0",
});
export const PSRD2_QUANTILE_PROBABILITIES: readonly number[] = Object.freeze([
  0, 0.001, 0.01, 0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.55, 0.6, 0.7, 0.8,
  0.9, 0.95, 0.975, 0.99, 0.999, 1,
]);
export const PSRD2_QUANTILES: readonly number[] = Object.freeze([
  -0.993755932860514, -0.9234206602714042, -0.8243409486300636,
  -0.7908685731311131, -0.7409964622904881, -0.6487575424081553,
  -0.48254038301583296, -0.3222855036030713, -0.16131397774591355,
  -0.00043733163845874443, 0.08053485239273601, 0.16081844504211004,
  0.32137461130699774, 0.4820525560497572, 0.6480337535794202, 0.7405147540371,
  0.790927315929763, 0.8244710078300381, 0.9237598504247772, 0.9930859540643082,
]);
